### ISSUE TITLE
mvn install -P scala-2.12_spark-3.1.2 failed (using Azure DevOps Maven@3 task)

### ISSUE THREAD

**Issue by cd-bustamante** [mspnp/spark-monitoring#179]
# Cannot complete mvn Install -P scala-2.12_spark-3.1.2 using Azure DevOps Maven@3 task

I am trying to generate the two jar files (spark-listeners_3.1.2_2.12-1.0.0-sources.jar & spark-listeners-loganalytics_3.1.2_2.12-1.0.0-sources.jar)

I am importing this repo into an Azure DevOps repo, and from there I am creating a DevOps pipeline running in a Microsoft Hosted Agent (Ubuntu-latest), defined as follows

```yaml
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      ls -ltr /usr/lib/jvm/
      sudo apt install openjdk-8-jdk openjdk-8-jre

- task: Maven@3
  inputs:
    mavenPomFile: 'src/pom.xml'
    options: 'clean install -X -P scala-2.12_spark-3.1.2'
    publishJUnitResults: false
    javaHomeOption: 'Path'
    jdkDirectory: '/usr/lib/jvm/java-8-openjdk-amd64'
    mavenVersionOption: 'Default'
    mavenOptions: '-Xmx3072m'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

```

## This is the error I am receiving:

```log
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-jar-plugin:3.1.2:jar (default-jar) on project spark-listeners: You have to use a classifier to attach supplemental artifacts to the project instead of replacing them. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-jar-plugin:3.1.2:jar (default-jar) on project spark-listeners: You have to use a classifier to attach supplemental artifacts to the project instead of replacing them.

```

## Additional information
If I run the maven command from a bash@3 (as shown in the configuration below) I am able to generate both jar files.

```yml
trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      ls -ltr /usr/lib/jvm/
      sudo apt install openjdk-8-jdk openjdk-8-jre

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      mvn --version
      java -version
      sudo update-java-alternatives -s java-1.8.0-openjdk-amd64
      export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64/
      export PATH=$PATH:$JAVA_HOME
      mvn --version
      java -version
      mvn -f src/pom.xml install -P "scala-2.12_spark-3.1.2"
```
Have any of you tried to use Azure DevOps for the creation of the jar files?
Also please be aware that I have no previous experience with Maven.
Thank you very much for your project and for your support!
